### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by Jopo12321** [google-developer-training/android-basics-kotlin-cupcake-app#103]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack

**In which task and step of the codelab can this issue be found?**
5. Send the order -> Step 4.

**Describe the problem**
The way of checking if there's an app that could handle the intent is deprecated for API 30+.
It is working at the moment but it might not work as intended in some cases.

**Versions**
_Android Studio version:_ 2022.3.1
_API version of the emulator:_ 33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/assets/68444345/766a36f2-9efb-4cff-af33-795b2cb72751)

**Comment by jlulovics** [comment]
thank you for your feedback - this content has been deprecated
