### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by MoeJoeMJ** [google-developer-training/android-basics-kotlin-cupcake-app#105]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Unit 3, Pathway 4, Step 7

**Describe the problem**
Typo in the 12th line of the step 7.
The date actually parses to "Wed, Jan 4"
"If the date is January 4 in 2018, the pattern string "EEE, MMM d" parses to "Wed, Jul 4""

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jlulovics** [comment]
thank you for your feedback - this content has been deprecated
