### ISSUE TITLE
Android Basics: Navigation backstack - instructions formatting error

### ISSUE THREAD

**Issue by charles-allen** [google-developer-training/android-basics-kotlin-cupcake-app#11]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack

**In which task and step of the codelab can this issue be found?**
"4. Learn about tasks and back stack"

**Describe the problem**
There are 3 consecutive headings (I suspect the latter 2 should be list items):

> ## Modify the back stack in the Cupcake app
> ## Modify the FlavorFragment, PickupFragment, and SummaryFragment classes and layout files in order to offer a Cancel order button to the user.
> ## Add navigation action

**Comment by kkuan2011** [comment]
Fixed now, thank you!
