### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by tonywmk** [google-developer-training/android-basics-kotlin-cupcake-app#13]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**
in *Add Navigation to the flavor and pickup fragments*, 2nd point.

**Describe the problem**
A "t" is missing in the ID
=> R.id.action_flavorFragment_to_pickupFragmen

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@tonywmk 
Thank you so much for reporting this issue. This is fixed and will be published soon.
