### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-cupcake-app#14]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**
Task: 3
Step: "Update title in app bar"
Sub-step: 4

**Describe the problem**
The text "Open navigataion/nav_graph.xml" should read "Open navigation/nav_graph.xml" 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-04-19 092202](https://user-images.githubusercontent.com/61388284/115243677-2d269d80-a0f1-11eb-958b-404b8a078a59.jpg)

**Comment by jhansitavva** [comment]
@hassan0599 
Thank you so much for reporting this issue. This is fixed and will be published soon.
