### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-cupcake-app#15]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Task: 7
Step: "Update the layout to display pickup options"

**Describe the problem**
The text "...view model, update the PickupFragment to display..." should read "...view model, update the fragment_pickup.xml to display..."

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-04-20 171611](https://user-images.githubusercontent.com/61388284/115466304-e5416c80-a1fd-11eb-9dbb-03484899bd76.jpg)

**Comment by jhansitavva** [comment]
@hassan0599 
Thank you so much for reporting this issue. This is fixed and will be published soon.
