### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-cupcake-app#18]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**
Add Navigation to the flavor and pickup fragments

**Describe the problem**
In the sentece, "Use the action ID, R.id.action_flavorFragment_to_pickupFragmen and make sure this ID matches the action declared in your nav_graph.xml." the id of the action is missing a 't' at the end.

It's correct in the following code block, but with a missing 't' in the description.

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by jhansitavva** [comment]
@KKH-tw 
Thank you so much for reporting this issue. This is fixed and will be published soon.
