### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-cupcake-app#19]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel#6

**In which task and step of the codelab can this issue be found?**
"9. Run your app again, notice today's date is selected by default."

**Describe the problem**
After adding the `init ` block and removing the initial values, it showed the NullPointerException error, as quoted below.

"7. Add an init block to the class, and call the new method resetOrder() from it."
"8. Remove the initial values from the declaration of the properties in the class. Now you are using the init block to initialize the properties when an instance of OrderViewModel is created."
"9. Run your app again, notice today's date is selected by default."

The error in Logcat:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.MutableLiveData.setValue(java.lang.Object)' on a null object reference
        at com.example.cupcake.model.OrderViewModel.resetOrder(OrderViewModel.kt:56)
        at com.example.cupcake.model.OrderViewModel.<init>(OrderViewModel.kt:11)

**Steps to reproduce?**
As stated above.

**Versions**
_Android Studio version:_ 4.2.1
_API version of the emulator:_ 30

**Additional information**
Nil.

**Comment by citrusella** [comment]
Try moving the init down below the variables. I had this issue in a previous codelab at some point and happened upon that as a viable solution via some Github issue somewhere and that fixed it here as well.

(But they probably should make clear at some point in these lessons about proper placement of the init block to avoid this, considering I've done it twice now even though I had looked it up after the first time the codelab was no help in figuring out my error.)

**Comment by KKH-tw** [comment]
@citrusella Thank you for the solution  :)

I also found the reason for this error in the Kotlin docs:

> During an instance initialization, the **initializer blocks** are executed in the **same order** as they appear in the **class body**, interleaved with the property initializers: ...

https://kotlinlang.org/docs/classes.html#constructors

After moving the `init` block to an appropriate location, it compiles succeasfully.
