### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by M-Phuykong** [google-developer-training/android-basics-kotlin-cupcake-app#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-navigation-backstack#3

**In which task and step of the codelab can this issue be found?**
4./ Learn about tasks and back stack problem

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Text_Error](https://user-images.githubusercontent.com/53167700/121784093-2772a300-cbdc-11eb-8df5-df24b47e9835.JPG)

**Using Google Chrome

**Comment by kkuan2011** [comment]
Fixed now, thank you!
