### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by gitgrimbo** [google-developer-training/android-basics-kotlin-cupcake-app#23]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**

Step 3

**Describe the problem**

> In FlavorFragment.kt, inside the goToNextScreen() method, replace the code displaying the toast to navigate to the pickup fragment. Use the action ID, R.id.action_flavorFragment_to_pickupFragmen and make sure this ID matches the action declared in your nav_graph.xml.

`R.id.action_flavorFragment_to_pickupFragmen` needs a trailing 't'.  Should be `R.id.action_flavorFragment_to_pickupFragment`.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by kkuan2011** [comment]
Thank you, fixed and will be published soon.
