### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by Skwyzzie** [google-developer-training/android-basics-kotlin-cupcake-app#28]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel

**In which task and step of the codelab can this issue be found?**
Step 2: Starter code walkthrough

**Describe the problem**
In the section describing the AppCompatActivity, the definitions change from
     -AppCompatActivity(R.layout.activity_main) to
     -setContentView(R.layout.main_activity)
The resource id name changes and might confuse new users

**Steps to reproduce?**
1. Go to codelab referenced above
2. Go to Step 2 
3. Notice the error under the starter code walkthrough section

**Comment by kkuan2011** [comment]
Oops this is a typo and should be fixed. Same as #29.
