### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by capptain-bogoslov** [google-developer-training/android-basics-kotlin-cupcake-app#29]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#1

**In which task and step of the codelab can this issue be found?**
Steo 2

**Describe the problem**
In code example instead of

`setContentView(R.layout.main_activity)`

it should be 
 `setContentView(R.layout.activity_main)`

**Steps to reproduce?**
1. Go to codelab
2. Click on Step 2
3. See typo error in code

**Additional information**
![Στιγμιότυπο από 2021-08-16 09-11-21](https://user-images.githubusercontent.com/79518127/129518962-acb7cf5c-0fd8-4476-ad04-d59d81a4a941.png)

**Comment by kkuan2011** [comment]
Good catch! Fixed and will be published soon, thank you!
