### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by ArpitChhabra** [google-developer-training/android-basics-kotlin-cupcake-app#33]
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Step 7

**Describe the problem**
I'm new to Kotlin and has a very basic knowledge of init block. In step 7, I was instructed to add the init block in the OrderViewModel class and I did it. Suddenly my app started to crash. Then I figured it out that it does matter that where I put the init block. In the init block a method is being called which reference a property of the OrderViewModel class and i put the init block above the properties declarations so i started to get null pointer exceptions. Then I thought to put the init block below the properties declarations and it worked. The issue is You guys should have told the students to put the init block below the properties declarations.

**Versions**
_Android Studio version:_  doesn't matter
_API version of the emulator:_  doesn't matter

**Comment by cheekean2012** [comment]
In resetOrder() method inside change _date.value = dateOptions[0] to _date.value = ""
Here is how my fixed this issue

**Comment by cheekean2012** [comment]
> https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#6
> 
> **In which task and step of the codelab can this issue be found?**
> Step 7
> 
> **Describe the problem**
> I'm new to Kotlin and has a very basic knowledge of init block. In step 7, I was instructed to add the init block in the OrderViewModel class and I did it. Suddenly my app started to crash. Then I figured it out that it does matter that where I put the init block. In the init block a method is being called which reference a property of the OrderViewModel class and i put the init block above the properties declarations so i started to get null pointer exceptions. Then I thought to put the init block below the properties declarations and it worked. The issue is You guys should have told the students to put the init block below the properties declarations.
> 
> **Versions**
> _Android Studio version:_ doesn't matter
> _API version of the emulator:_ doesn't matter



> https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#6
> 
> **In which task and step of the codelab can this issue be found?**
> Step 7
> 
> **Describe the problem**
> I'm new to Kotlin and has a very basic knowledge of init block. In step 7, I was instructed to add the init block in the OrderViewModel class and I did it. Suddenly my app started to crash. Then I figured it out that it does matter that where I put the init block. In the init block a method is being called which reference a property of the OrderViewModel class and i put the init block above the properties declarations so i started to get null pointer exceptions. Then I thought to put the init block below the properties declarations and it worked. The issue is You guys should have told the students to put the init block below the properties declarations.
> 
> **Versions**
> _Android Studio version:_ doesn't matter
> _API version of the emulator:_ doesn't matter

And another issue is your declare property after init method.
For example:
init {
  resetOrder()
}

val dateOptions = getPickupOptions()

If you want to fix this issue, your property must declare on the top

**Comment by ArpitChhabra** [comment]
> In resetOrder() method inside change _date.value = dateOptions[0] to _date.value = ""
> Here is how my fixed this issue

Actually I fixed it. I think where you put the init block that matters. So I put it right below the class properties, that's how I fixed it
