### ISSUE TITLE
Android Basics: Shared ViewModel - Proyect version is the finished product

### ISSUE THREAD

**Issue by Sarl98** [google-developer-training/android-basics-kotlin-cupcake-app#36]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel

**In which task and step of the codelab can this issue be found?**
Starter app overview, step 2 - Get the code

**Describe the problem**

When you download the code, you automatically download the main branch, which is the complete version of the app and it can't be used to learn the unit since it is already complete and has all of the missing pieces. You can set the correct branch in git but someone who's not used to using git(or doesn't know about version control) will not be able to use the code to learn by doing.

**Steps to reproduce?**
1. Go to the link to the Github on the codelab
2. Click on download to zip
3. Open the project and see it is the complete version

**Versions**
_Android Studio version: Not relevant
_API version of the emulator: Not relevant

**Additional information**
It can easily be changed by just doing a checkout to the correct branch but it might be useful to explain that on the codelab

**Comment by mirianfonkam** [comment]
Hi @Sarl98! There is an alternative method without using git. 

1. Go to this link: [https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/tree/starter](https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/tree/starter)
![Cupcake App Starter Branch](https://user-images.githubusercontent.com/28691174/134773101-7102dfe3-03c6-43cd-a96c-0e3e022a4724.png)
2. Click on the green button "_Code_" > "_Download Zip_"
3. Assert that the folder downloaded ends with "_-starter_"
![Folder of Starter Branch](https://user-images.githubusercontent.com/28691174/134772804-f7631876-aac8-40ea-be90-58a9086146c4.png)
4. Open the project and note it is the _incomplete_ version

**Comment by kkuan2011** [comment]
@Sarl98 were you able to get the starter code? You can retrieve it from the starter branch here as @mirianfonkam mentioned. https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/tree/starter

Otherwise, yes the main branch does have the complete solution.
https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/tree/main

Let us know if the instructions in the codelab are incorrect!
