### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by sbswami** [google-developer-training/android-basics-kotlin-cupcake-app#37]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack#4

**In which task and step of the codelab can this issue be found?**
In `Send the order` -> step 6.

**Describe the problem**
In `getQuantityString(R.string.cupcakes, 1, 1)` the resources id shouldn't be `R.string.cupcakes`, it should be `R. plurals.cupcakes`

**Comment by kkuan2011** [comment]
Thank you! Duplicate of #16 and will be fixed.
