### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by hyatt-andydelso** [google-developer-training/android-basics-kotlin-cupcake-app#38]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**
3. Complete the Navigation Graph

**Describe the problem**
Pulling down "starter" branch for both this and the last app provides pretty much completed code. Thus the person is learning nothing about how to do things for themselves. In this specific instance, it tells you to start making the navigation graph. Well, the graph is already done for me.

**Steps to reproduce?**
1. Go to specified codelab URL AFTER pulling down starter branch code from the repo this issue is located in
2. open in Android studio
3. See this issue with starter code already being completed

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_ N/A

**Additional information**
![Screen Shot 2021-10-12 at 9 21 01 AM](https://user-images.githubusercontent.com/80729087/136974049-6a7213e0-d0c3-4cab-94ef-fc84440f570b.png)

**Comment by kkuan2011** [comment]
Hello @hyatt-andydelso! Did you pull the starter branch for the Cupcake app? 
https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/tree/starter

It should contain the 4 fragments but there shouldn't be any actions yet in the navigation graph which are part of the codelab steps.
