### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by nicholeb** [google-developer-training/android-basics-kotlin-cupcake-app#4]
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack#4

**In which task and step of the codelab can this issue be found?**
Task: 5 Send the order
Step: 9 Modify submitOrder

**Describe the problem**

I think the code snippet in this step has an error: "sharedViewModel.priceString.value.toString()" in orderSummary should be sharedViewModel.price.value.toString()

**Comment by jhansitavva** [comment]
@nicholeb 
Thank you so much for reporting this issue. This is fixed and will be published soon.
