### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by DFilkins919** [google-developer-training/android-basics-kotlin-cupcake-app#49]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#7

**In which task and step of the codelab can this issue be found?**
Task 8 Step 4

**Describe the problem**
When testing the app, the same day pickup charge is being applied on the "Choose Flavor" screen. This is due to resetOrder() being called in the init block setting the _date value to dateOptions[0] which is always today. The code needs to either exclude _date in resetOrder() and check the first radio button automatically only when going into the "Choose Pickup Date" screen or the updatePrice() will need to be updated with a flag to differentiate whether setQuantity() or setDate() called updatePrice(). 

For example if setDate() calls updatePrice() and passes in a flag value of TRUE then that flag can be added to the IF condition to apply the same day pickup charge.

**Steps to reproduce?**
1. Run the App from the solution code in Task 10
2. Click any of the buttons on the Cupcake screen
3. You will see the subtotal automatically applies the $3 fee for same day pickup before a date was selected.

**Versions**
_Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
_API version of the emulator: 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Android Basics Error](https://user-images.githubusercontent.com/23108592/143790869-f7ed2c5b-6d42-498e-99d2-196c615f2ba1.JPG)

**Comment by DemisChan** [comment]
Same issue here

**Comment by DemisChan** [comment]
@DFilkins919 
I believe I found what we both omitted accidentally.
go to your OrderViewModel and check if you have the `updatePrice` in the `setDate` function.
I accidentally forgot and that was my problem
it should be like this:

```    
fun setDate(pickupDate: String) {
    _date.value = pickupDate
    updatePrice()
}
```
