### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by JavierMeisnitzer** [google-developer-training/android-basics-kotlin-cupcake-app#5]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack?hl=es&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fhl%3Des%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-navigation-backstack#4

**In which task and step of the codelab can this issue be found?**
5. Send the order
 - 9. The full sendOrder() method should look like the following:

**Describe the problem**

this line of code -> sharedViewModel.priceString.value.toString() 
should be -> sharedViewModel.price.value.toString()

**Steps to reproduce?**
1. Go to... https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack?hl=es&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fhl%3Des%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-navigation-backstack#4
2. Click on...
fun sendOrder() {
    val numberOfCupcakes = sharedViewModel.quantity.value ?: 0
    val orderSummary = getString(
        R.string.order_details,
        resources.getQuantityString(R.plurals.cupcakes, numberOfCupcakes, numberOfCupcakes),
        sharedViewModel.flavor.value.toString(),
        sharedViewModel.date.value.toString(),
        sharedViewModel.priceString.value.toString()
    )

    val intent = Intent(Intent.ACTION_SEND)
        .setType("text/plain")
        .putExtra(Intent.EXTRA_SUBJECT, getString(R.string.new_cupcake_order))
        .putExtra(Intent.EXTRA_TEXT, orderSummary)
    
    if (activity?.packageManager?.resolveActivity(intent, 0) != null) {
        startActivity(intent)
    }
} 
3. See error...
line -> sharedViewModel.priceString.value.toString()

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_ no

**Additional information** my first report
_Include screenshots if they would be useful in clarifying the problem._
https://gyazo.com/47ebe67bf9b7030467962c176b8c3335

**Comment by jhansitavva** [comment]
@JavierMeisnitzer 
Thank you for reaching out to us.
This should be fixed now.
