### ISSUE TITLE
Solution Code missing test suite

### ISSUE THREAD

**Issue by TiredEarlyBird** [google-developer-training/android-basics-kotlin-cupcake-app#50]
[**URL of codelab**](https://developer.android.com/codelabs/android-basics-kotlin-test-viewmodel-and-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-viewmodel-and-livedata#6)

**In which task and step of the codelab can this issue be found?**
Unit 3: Pathway 4: Advanced navigation app examples

**Describe the problem**
In step 7 there is a link to the solution code, but the JUnit test classes are missing or the link is wrong

**Comment by alu0100207385** [comment]
Yeah, the link is there, but you have to change to the test_solution branch to check the file. 

Is this what you are looking for? 
> https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/blob/test_solution/app/src/test/java/com/example/cupcake/ViewModelTests.kt
