### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by rlmar123** [google-developer-training/android-basics-kotlin-cupcake-app#51]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-navigation-backstack#2)

3. Implement Up button behavior

 override fun onSupportNavigateUp(): Boolean { return navController.navigateUp() || super.onSupportNavigateUp() }

app crashes when this line is added and the up button is hit

**Versions**
_Android Studio version:_ Artic Fox 2020.3.1
Pixel 4 XL API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by alu0100207385** [comment]
Hi there,
Could you share your crash log? (Android console log)
Thanks :)

**Comment by rlmar123** [comment]
Hi Aaron, I think I found the problem. It looks like private lateinit var navController: NavController is never initialized.

Here is a copy of my code : 

Here is what I am seeing in the log :




    On Thursday, December 30, 2021, 12:00:04 PM EST, Aaron Socas Gaspar ***@***.***> wrote:  
 
 


Hi there,
Could you share your crash log? (Android console log)
Thanks :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
