### ISSUE TITLE
Android Kotlin Basics: Test ViewModels and LiveData

### ISSUE THREAD

**Issue by shanxg** [google-developer-training/android-basics-kotlin-cupcake-app#53]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-test-viewmodel-and-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-viewmodel-and-livedata#5

**In which task and step of the codelab can this issue be found?**
3

**Describe the problem**

The 3rd step tells to make a price check test and add this code : 
 - "assertEquals("$27.00", viewModel.price.value)"

Knowing that the transformation happening in OrderViewModel will format to the current locale currency info, which for me is BR info, i fixed so it would fit my nationality, then i tried :

  - "assertEquals("R$27.00", viewModel.price.value)"
  - "assertEquals("R$ 27.00", viewModel.price.value)"
  - "assertEquals("R$27,00", viewModel.price.value)"
  - "assertEquals("R$ 27,00", viewModel.price.value)"
 
Then i got the error on the images attached.

**Steps to reproduce?**
1. Go to...  src>androidTest>ViewModelTests 
2. Click on... Run "price_twelve_cupcake()"
3. See error... 
expected:<R$[ ]27,00> but was:<R$[ ]27,00>
Expected :R$ 27,00
Actual   :R$ 27,00
<Click to see difference>

org.junit.ComparisonFailure: expected:<R$[ ]27,00> but was:<R$[ ]27,00>

**Versions**
_Android Studio version:_ 

Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.featureSuggester (211.205), org.intellij.plugins.markdown (211.7142.37)

_API version of the emulator:_ 

Android version : 11.0(R) - API 30
Emulator Version : 31.2.6-8100890

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**This is my Test code:**

![image](https://user-images.githubusercontent.com/63316622/152351799-89055e64-c441-4401-accf-b2fab4d4a0c3.png)

**This is the error notification:**

![image](https://user-images.githubusercontent.com/63316622/152352177-5bb9cda8-fab1-4759-b8cf-095612021114.png)

**Here is the error description:**

![image](https://user-images.githubusercontent.com/63316622/152351916-f0bea2ce-7c77-4b93-9a41-1b3310a3d9ea.png)

**Comment by AlveZs** [comment]
I had the same problem and fixed it with the same ```NumberFormat``` strategy on ```price_twelve_cupcakes```.

```
@Test
fun price_twelve_cupcakes() {
    ...
    assertEquals(
        NumberFormat.getCurrencyInstance().format(27),
        viewModel.price.value
    )
}
```
