### ISSUE TITLE
Android Basics: MORE STARTER CODE ERRORS, ANOTHER PROJECT!    CUPCAKE

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-cupcake-app#55]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**

STEP 3

   This is the Cupcake app.    This is the 4 starter project with a error and no way to import it!
I am not doing anymore Android studio until you fix your projects.  

**Describe the problem**

see  the screen shots.   what is red has no way to import, so what am I supposed to do?   Can you add it?  I have other emails with other started projects I can't do because they are full of errors!

<img width="1440" alt="Screen Shot 2022-02-07 at 2 16 28 PM" src="https://user-images.githubusercontent.com/91148652/152865175-e76803d8-5c04-4a8e-b462-081e9c8e5806.png">
<img width="1440" alt="Screen Shot 2022-02-07 at 2 16 35 PM" src="https://user-images.githubusercontent.com/91148652/152865188-9943446d-e6c3-4640-bcef-a671f1c08d59.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by EleoXDA** [comment]
Hello,

It looks like you didn't download the "starter package", as in there, the MainActivity.kt is empty. To be sure that you downloaded the starter package when navigating to the GitHub link, be sure to choose "starter package" in branch options:
![image](https://user-images.githubusercontent.com/27622683/157111021-f83ab3e4-f5e1-4758-8e4d-24b94ba5f8c0.png)

In case you added the code yourself, this is not the error of the **starter package**, but a user error.

Try not to copy-paste by reading every line on CodeLab. Try to understand the reasons they are there and why it is written like that.

In case of your issue, to call setupActionBarWithNavController(navController) you need to import:
`import androidx.navigation.ui.setupActionBarWithNavController
`
In your case you have imported:
`import androidx.navigation.ui.NavigationUI.setupActionBarWithNavController`

Try this fix and report back please.

**Comment by jh115424** [comment]
Thanks, this was actually resolved, but I am waiting for another reply on a different project.  I sent it to Guilhermo, but did not hear back.      It is on the lunch tray app.    I ran the project and got a compile error.

There screen shot is in the Github.com "Issues" section.   I posted the reply 4 days ago.  Just scroll all the way down and you will see the Logcat.

I can't send the screen shot here, because it does not open on your end from this email.   Check my reply in Github and you will see the screen shot for the lunch tray app.


It is Lunchtray app #20

thanks




Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:1d72284e-c2fc-4c10-88dd-9da303b7f8e6]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
I am also stuck on this part...it is the Water Me!  app

I have been stuck here for 3 days now.    What else am I missing?

please help.

thanks



// TODO: create a Data instance with the plantName passed to it

val data = Data.Builder(WaterReminderWorker to scheduleReminder(plantName =)



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:36e4dbf3-a2e8-4339-b4ff-9e9e6e87e6c6]<https://your.tradeinvalet.com/tdhe0j>

________________________________
