### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by hubberlw** [google-developer-training/android-basics-kotlin-cupcake-app#57]
**URL of codelab**
https://github.com/google-developer-training /
[android-basics-kotlin-cupcake-app](https://github.com/google-developer-training/android-basics-kotlin-cupcake-app)

**In which task and step of the codelab can this issue be found?**
9. Setup click listeners using listener binding

**Describe the problem**
In the layout xml files for fragment_flavor.xml and fragment_pickup.xml, the lines
android:onClick="@{() -> flavorFragment.goToNextScreen()}"
android:onClick="@{() -> pickupFragment.goToNextScreen()}"
do not compile. "goToNextScreen() results in "Cannot find identifier".

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
![Screenshot 2022-02-10 011439](https://user-images.githubusercontent.com/55035960/153348917-cab3c285-acdc-4de7-9fe9-9f1440664b28.jpg)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
Bumblebee 2021.1.1 Patch 1
Build # AI-211.7628.21.2111.8139111 on Feb 1, 2022

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by EleoXDA** [comment]
Hello.

Do you have these lines in FlavorFragment.kt?
```
    fun goToNextScreen() {
        findNavController().navigate(R.id.action_flavorFragment_to_pickupFragment)
    }
```
