### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by behj-han19** [google-developer-training/android-basics-kotlin-cupcake-app#6]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-navigation-backstack#4

**In which task and step of the codelab can this issue be found?**
Task 5
 sharedViewModel.priceString.value.toString()
should be ->  sharedViewModel.price.value.toString()

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published.
