### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by Raikonif** [google-developer-training/android-basics-kotlin-cupcake-app#64]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**
Step 3 complete navigation bar - Update title in the app bar

**Describe the problem**
Attribute in NavGraph isn't working, don't change the AppBar Name when I change the strings

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio Chipmunk | 2021.2.1
_API version of the emulator:_ 
API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/66791443/168696719-0aac2d01-8af0-44e6-9903-acad44587ab5.png)

**Comment by eclipsn** [comment]
Carefully consider which fun onCreate you are overriding, if it looks like this fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?), then this is not what you need. Just copy and paste what is written in codelab. I mean the block with MainActivity.
