### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by eclipsn** [google-developer-training/android-basics-kotlin-cupcake-app#72]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#2

**In which task and step of the codelab can this issue be found?**
In 3 stage,"Update title in app bar" this is last task

**Describe the problem**
Complete all stages and see how the result does NOT match.

**Versions**
_Android Studio version:_ 2021.2.1 Patch 1 Build #AI-212.5712.43.2112.8609683, built on May 12, 2022
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by eclipsn** [comment]
I found the problem: ide suggested import android.os.PersistableBundle fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?). And if I fix on fun onCreate(savedInstanceState: Bundle?) then everything works.

**Comment by adam10414** [comment]
@eclipsn, thank you!
