### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by vexijio** [google-developer-training/android-basics-kotlin-cupcake-app#88]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#7

**In which task and step of the codelab can this issue be found?**
Step: Format price with LiveData transformation 1. 

**Describe the problem**

" In OrderViewModel class, change the backing property type to LiveData<String> instead of LiveData<Double>. 
private val _price = MutableLiveData<Double>()
val price: LiveData<String> 
"

Is the 'price' a backing property? As far as i know, the '_price' is a backing property, and 'price' is a regular one? Am I mistaken?

**Comment by dongnd95** [comment]
'price' is a backing property declared to access value of private property '_price'.
