### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by AlexandrePlus** [google-developer-training/android-basics-kotlin-cupcake-app#9]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack#4 

**In which task and step of the codelab can this issue be found?**
5. Send the order > 9. Then format the order_details... 

**Describe the problem**
It is written `sharedViewModel.priceString.value.toString()`  instead of `sharedViewModel.price.value.toString()`

**Comment by jhansitavva** [comment]
@AlexandrePlus 
Thank you so much for reporting this issue. This is fixed and will be published soon.
