### ISSUE TITLE
Transformations.map 

### ISSUE THREAD

**Issue by ParkerS6** [google-developer-training/android-basics-kotlin-cupcake-app#91]
(https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#7)

Step 8 Format Price with LiveData transformation

When using lifecycle implementation version 2.6.1 the transformations function can no longer be used and you must instead use example.map or example.switchMap rather than Transformations.map

**Comment by rishabhagg7** [comment]
Which version of the androidx.lifecycle library are you using? If it's 2.6.0 or newer then you should replace Transformations.map(_price) { } with _price.map { }. See [the changelog](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.6.0) for version 2.6.0.
