### ISSUE TITLE
Android Basics: Shared ViewModel

### ISSUE THREAD

**Issue by Napharcos** [google-developer-training/android-basics-kotlin-cupcake-app#99]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-shared-viewmodel#9

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

I got error after running my project.

I get the same error when running the solution code:

https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/tree/viewmodel

**Steps to reproduce?**
1. Go to...

download solution code

3. Click on...

run

5. See error...

"Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.4.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.4.0)
     Duplicate class androidx.lifecycle.ViewModelProviderKt found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.4.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.4.0)
     Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.4.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.4.0)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights."

**Versions**
_Android Studio version:_ 

Flamingo, 2022.2.1

_API version of the emulator:_ 

33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Ninidze1** [comment]
check if helps: https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/pull/100

**Comment by Napharcos** [comment]
https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/pull/100

This fixes the error. Thank you very much.
